version: "2"
services:
  web:
    build: .
    ports:
      - "5000:80"
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/keycap
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=keycap
